baseURL = 'http://example.org/'
languageCode = 'en-uk'
title = 'Oasys'
theme = "oasys"
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
    [markup.goldmark.extension]
      linkify = false